# Generated by Django 5.1.6 on 2025-02-13 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(choices=[('definite', 'Bestimmter Artikel'), ('indefinite', 'Unbestimmter Artikel')], max_length=20)),
                ('case', models.CharField(choices=[('nominativ', 'Nominativ'), ('akkusativ', 'Akkusativ'), ('dativ', 'Dativ'), ('genitiv', 'Genitiv')], max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('singular', models.CharField(max_length=100)),
                ('plural', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conjunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjunction_type', models.CharField(choices=[('coordinating', 'Nebenordnende Konjunktion'), ('subordinating', 'Unterordnende Konjunktion')], max_length=20)),
                ('case_governed', models.CharField(choices=[('nominativ', 'Nominativ'), ('akkusativ', 'Akkusativ'), ('dativ', 'Dativ'), ('genitiv', 'Genitiv')], max_length=20)),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronoun_type', models.CharField(choices=[('personal', 'Personalpronomen'), ('possessive', 'Possessivpronomen'), ('demonstrative', 'Demonstrativpronomen'), ('relative', 'Relativpronomen'), ('interrogative', 'Fragepronomen')], max_length=20)),
                ('case', models.CharField(choices=[('nominativ', 'Nominativ'), ('akkusativ', 'Akkusativ'), ('dativ', 'Dativ'), ('genitiv', 'Genitiv')], max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('singular', models.CharField(max_length=100)),
                ('plural', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GermanWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_form', models.CharField(max_length=100)),
                ('word_class', models.CharField(choices=[('NOUN', 'Substantiv'), ('VERB', 'Verb'), ('ADJ', 'Adjektiv'), ('CONJ', 'Konjunktion'), ('PREP', 'Präposition')], max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('metadata', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Declination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(choices=[('nominativ', 'Nominativ'), ('akkusativ', 'Akkusativ'), ('dativ', 'Dativ'), ('genitiv', 'Genitiv')], max_length=20)),
                ('singular', models.CharField(max_length=100)),
                ('plural', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.germanword')),
            ],
        ),
    ]
