# Generated by Django 5.1.6 on 2025-02-08 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GermanWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_form', models.CharField(max_length=100)),
                ('word_class', models.CharField(choices=[('NOUN', 'Substantiv'), ('VERB', 'Verb'), ('ADJ', 'Adjektiv'), ('CONJ', 'Konjunktion'), ('PREP', 'Präposition')], max_length=50)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('metadata', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Declination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(choices=[('nominativ', 'Nominativ'), ('akkusativ', 'Akkusativ'), ('dativ', 'Dativ'), ('genitiv', 'Genitiv')], max_length=20)),
                ('singular', models.CharField(max_length=100)),
                ('plural', models.CharField(blank=True, max_length=100, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.germanword')),
            ],
        ),
    ]
