# Generated by Django 5.1.6 on 2025-02-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='germanword',
            name='pronoun_type',
            field=models.CharField(blank=True, choices=[('PERS', 'Personalpronomen'), ('POSS', 'Possessivpronomen'), ('DEM', 'Demonstrativpronomen'), ('REL', 'Relativpronomen'), ('INT', 'Interrogativpronomen')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='germanword',
            name='word_class',
            field=models.CharField(choices=[('NOUN', 'Substantiv'), ('VERB', 'Verb'), ('ADJ', 'Adjektiv'), ('CONJ', 'Konjunktion'), ('PREP', 'Präposition'), ('PRON', 'Pronomen')], max_length=50),
        ),
    ]
