# Generated by Django 5.1.6 on 2025-02-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_germanword_pronoun_type_alter_germanword_word_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='germanword',
            name='pronoun_type',
        ),
        migrations.AlterField(
            model_name='declination',
            name='plural',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='germanword',
            name='word_class',
            field=models.CharField(choices=[('NOUN', 'Substantiv'), ('VERB', 'Verb'), ('ADJ', 'Adjektiv'), ('CONJ', 'Konjunktion'), ('PREP', 'Präposition')], max_length=50),
        ),
    ]
