# Generated by Django 5.1.6 on 2025-02-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_auto_20250213_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germanword',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
