# Generated by Django 5.1.6 on 2025-02-13 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_alter_germanword_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjectiveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(choices=[('nominativ', 'Nominativ'), ('akkusativ', 'Akkusativ'), ('dativ', 'Dativ'), ('genitiv', 'Genitiv')], max_length=20)),
                ('number', models.CharField(choices=[('singular', 'Singular'), ('plural', 'Plural')], max_length=20)),
                ('gender', models.CharField(choices=[('masculine', 'Maskulinum'), ('feminine', 'Femininum'), ('neuter', 'Neutrum')], max_length=20)),
                ('form', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.germanword')),
            ],
            options={
                'unique_together': {('word', 'case', 'number', 'gender')},
            },
        ),
    ]
